// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Vacancies.DataAccess;

namespace Vacancies.DataAccess.Migrations
{
    [DbContext(typeof(VacanciesContext))]
    [Migration("20181126123139_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vacancies.DataModel.Entities.Vacancie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contact");

                    b.Property<DateTime>("Created_at");

                    b.Property<string>("Description");

                    b.Property<string>("Employment");

                    b.Property<string>("IdHH");

                    b.Property<string>("Name");

                    b.Property<string>("OrganisationName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Salary");

                    b.HasKey("Id");

                    b.ToTable("Vacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
